PricerBundle\Entity\OriginalPriceList:
    type: entity
    table: null
    repositoryClass: PricerBundle\Repository\OriginalPriceListRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
            nullable: false
    fields:
        vendorCode:
            type: string
            length: '128'
            nullable: false
        brand:
            type: string
            length: '128'
            nullable: false
        name:
            type: string
            length: '128'
            nullable: false
        description:
            type: text
            nullable: true
        price:
            type: float
            nullable: false
            options:
                unsigned: true
        quantity:
            type: smallint
            nullable: false
            options:
                unsigned: true
    manyToOne:
        priceList:
            targetEntity: PricerBundle\Entity\PriceList
            inversedBy: originalPrice
            joinColumns:
                priceList_id:
                    referensedColumnName: id
                    onDelete: SET NULL
                    nullable: false;
        user:
            targetEntity: PricerBundle\Entity\User
            inversedBy: originalPriceList
            joinColumns:
                user_id:
                    referensedColumnName: id
                    nullable: false
                    options:
                        unsigned: true
    oneToOne:
        readyPriceList:
            targetEntity: PricerBundle\Entity\ReadyPriceList
            mappedBy: originalPriceList
    lifecycleCallbacks: {  }