PricerBundle\Entity\PriceList:
    type: entity
    table: null
    repositoryClass: PricerBundle\Repository\PriceListRepository
    uniqueConstraints:
        unique_user_supplier_name:
            columns: [ user_id, supplier_id, name ]
        unique_user_supplier_code:
            columns: [ user_id, supplier_id, code ]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '128'
            nullable: false
        code:
            type: string
            length: 24
            nullable: false
        filePath:
            type: string
            length: '128'
            nullable: false
    manyToOne:
        supplier:
            targetEntity: PricerBundle\Entity\Supplier
            inversedBy: priceList
            joinColumns:
                supplier_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false
        user:
            targetEntity: PricerBundle\Entity\User
            inversedBy: priceList
            joinColumns:
                user_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false

    oneToMany:
        originalPrice:
            targetEntity: PricerBundle\Entity\OriginalPriceList
            mappedBy: priceList
        priceSetting:
            targetEntity: PricerBundle\Entity\PriceSetting
            mappedBy: priceList
        readyPriceList:
            targetEntity: PricerBundle\Entity\ReadyPriceList
            mappedBy: priceList
    lifecycleCallbacks: {  }
