PricerBundle\Entity\Supplier:
    type: entity
    table: null
    repositoryClass: PricerBundle\Repository\SupplierRepository
    uniqueConstraints:
        unique_user_name:
            columns: [ user_id, name ]
        unique_user_code:
            columns: [ user_id, code ]

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '128'
            nullable: false
        code:
            type: string
            length: '128'
            nullable: false
        priceCurrency:
            type: string
            length: '3'
            nullable: true
        exchangeRate:
            type: float
            options:
                unsigned: true
            nullable: true
        marginRate:
            type: smallint
            options:
                unsigned: false
            nullable: false
    oneToMany:
        priceList:
            targetEntity: PricerBundle\Entity\PriceList
            mappedBy: supplier
        brandRuler:
            targetEntity: PricerBundle\Entity\BrandRuler
            mappedBy: supplier
        vendorCodeRuler:
            targetEntity: PricerBundle\Entity\VendorCodeRuler
            mappedBy: supplier
    manyToOne:
        user:
            targetEntity: PricerBundle\Entity\User
            inversedBy: supplier
            joinColumns:
                user_id:
                    referencedColumnName: id
                    options:
                        unsigned: true
                    nullable: false
    lifecycleCallbacks: {  }