<?php

namespace PricerBundle\Repository;

/**
 * BrandRulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandRulerRepository extends \Doctrine\ORM\EntityRepository
{
}
