<?php

namespace PricerBundle\Repository;

/**
 * MarginRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarginRateRepository extends AbstractPricerRepository
{
    public function getRatesByUserId($userId)
    {
        return $this->createQueryBuilder('mr')
            ->where('mr.user=' . (int)$userId)
            ->getQuery()
            ->getArrayResult();
    }
    
    protected function getTableName()
    {
        return 'margin_rate';
    }

}
