<?php

namespace PricerBundle\Repository;

use PricerBundle\Entity\PriceList;

/**
 * PriceSettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceSettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNormalizedSettings(PriceList $priceList)
    {
        $settingsFromDB = $this->findBy(array(
            'priceList' => $priceList
        ));
        $priceSettings = array();

        foreach ($settingsFromDB as $setting) {
            $priceSettings[$setting->getSettingKey()] = $setting->getSettingValue();
        }
        return $priceSettings;
    }

}
