<?php

namespace PricerBundle\Repository;

/**
 * ReadyPriceListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadyPriceListRepository extends AbstractPriceListRepository
{
    public function multipleInsert(array $data, array $params, array $priceSettings, $toClean = true)
    {
        if ($toClean) {
            $this->clearBy('priceList_id', $params['priceListId']);
        }

        $readyData = array();
        $placeHolders = '';
        foreach ($data as $row) {
            $readyData[] = $params['userId'];
            $readyData[] = $row['vendorCode'];
            $readyData[] = $row['brand'];
            $readyData[] = $row['name'];
            $readyData[] = $row['description'];
            $readyData[] = $row['price'];
            $readyData[] = $row['quantity'];
            $readyData[] = $row['parent_id'];
            $readyData[] = $params['priceListId'];
            $placeHolders .= ' (?, ?, ?, ?, ?, ?, ?, ?, ?),';
        }
        $query = "INSERT INTO {$this->getTableName()} (`user_id`, `vendor_code`, `brand`, `name`, `description`, `price`, `quantity`, 
               `originalPriceList_id`, `priceList_id`)  VALUES" . chop($placeHolders, ',');
        $connection = $this->getEntityManager()->getConnection();
        $connection->executeUpdate($query, $readyData);
    }

    public function findAllByPriceListId($priceListId)
    {
        return $this->createQueryBuilder('opl')
            ->where('opl.priceList='.$priceListId)
            ->getQuery()->
            getArrayResult();
    }

    protected function getTableName()
    {
        return 'ready_price_list';
    }
}
