<?php

namespace PricerBundle\Repository;

/**
 * VendorCodeRulerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorCodeRulerRepository extends \Doctrine\ORM\EntityRepository
{
}
